### ISSUE TITLE
Hello World CLI Example produces a NullPointerException while training.

### ISSUE THREAD

**Issue by arunchaganty** [hltfbk/EOP-1.2.3#3]
I have just installed EOP-1.2.3 using the `install.sh` script, which terminated successfully. Trying the hello world CLI example at https://github.com/hltfbk/EOP-1.2.3/wiki/Step-by-Step-Tutorial#Hello%20World! produces a null pointer exception while training.

I ran the following command:
```
java -Djava.ext.dirs=../EOP-1.2.3/ eu.excitementproject.eop.util.runner.EOPRunner \
     -config ./eop-resources-1.2.3/configuration-files/MaxEntClassificationEDA_Base+OpenNLP_EN.xml \
     -train\
     -trainFile ./eop-resources-1.2.3/data-set/English_dev.xml\
     -trainDir /tmp/EN/dev\
     -test\
     -text "The students had 15 hours of lectures and practice sessions on the topic of Textual Entailment." \
     -hypothesis "The students must have learned quite a lot about Textual Entailment."\
     -output ./eop-resources-1.2.3/results/
```
And got the following output.
```
Dec 07, 2016 11:54:33 AM eu.excitementproject.eop.core.MaxEntClassificationEDA initializeModel
INFO: The trained model will be stored in /.../Excitement-Open-Platform-1.2.3/target/EOP-1.2.3/eop-resources-1.2.3/model/MaxEntClassificationEDAModel_Base+OpenNLP_EN
Indexing events using cutoff of 1

        Computing event counts...  done. 0 events
        Indexing...  done.
Sorting and merging events... Done indexing.
Incorporating indexed data for training...
Exception in thread "main" java.lang.NullPointerException
        at opennlp.maxent.GISTrainer.trainModel(GISTrainer.java:263)
        at opennlp.maxent.GIS.trainModel(GIS.java:256)
        at opennlp.maxent.GIS.trainModel(GIS.java:223)
        at opennlp.maxent.GIS.trainModel(GIS.java:166)
        at eu.excitementproject.eop.core.MaxEntClassificationEDA.startTraining(MaxEntClassificationEDA.java:513)
        at eu.excitementproject.eop.util.runner.EOPRunner.runEOPTrain(EOPRunner.java:209)
        at eu.excitementproject.eop.util.runner.EOPRunner.run(EOPRunner.java:423)
        at eu.excitementproject.eop.util.runner.EOPRunner.main(EOPRunner.java:467)
```

Additionally, checking `/tmp/EN/dev`, I see that all the preprocessed files do exist there.

**Comment by rzanoli** [comment]
In the EDA's configuration file the default values of the trainDir parameter
is /tmp/EN/dev1/ while the same parameter in the command line that you are
using
is /tmp/EN/dev/

Change /tmp/EN/dev1/ to  /tmp/EN/dev/ in the config file so it should work

**Comment by arunchaganty** [comment]
Ah, thank you for catching that! It works now. I also made an edit to the tutorial page to use the trainDir `/tmp/EN/dev1` instead.
